agent:
    main_agent: "CFSearchAgent"
    training_strategy_agent: "UniformSampler"
    search_strategy_agent: "ArchitectureGeneratorSearcher"
    search_space_agent: "SPOS"

    criterion_agent: "LabelSmoothingCrossEntropy"
    hc_criterion_agent: "MSELoss"

search_utility:
    directly_search: True
    random_iteration: 10
    info_metric: "flops"
    target_hc: 27
    lowest_hardware_constraint: 20
    highest_hardware_constraint: 35
    prior_pool_size: 1


generator:
    hc_dim: 10
    tau_decay: 0.95
    epochs: 20

train:
    resume: True
    random_seed: 1234
    device: "cuda"
    ngpu: 1
    epochs: 0

    bn_track_running_stats: True
    bn_momentum: 0.1

criterion: 

dataset:
    dataset: "cifar100"
    dataset_path: "./data/"
    classes: 100
    input_size: 32

    batch_size: 32
    num_workers: 4
    train_portion: 0.8

optim:
    optimizer: "sgd"
    lr: 0.045
    weight_decay: 0.00004
    momentum: 0.9
    alpha: 0.9
    beta: 0.99

    scheduler: "cosine"
    decay_step: 10
    decay_ratio: 0.1

arch_optim:
    a_hc_weight: 0.0006
    a_optimizer: "adam"
    a_lr: 0.0001
    a_weight_decay: 0
    a_momentum: 0
    a_alpha: ""
    a_beta: 0.5

logs_path:
    logger_path: "./logs/"
    writer_path: "./logs/tb/"


experiment_path:
    resume_path: "./checkpoints/search_99.pth"
    checkpoint_root_path: "./checkpoints/"
    best_checkpoint_path: "./best_checkpoint.pth"

    lookup_table_path: "./lookup_table.json"
    searched_model_path: "./searched_model_architecture.npy"

    best_loss_generator_checkpoint_path: "./best_loss_generator_checkpoint.pth"
    best_acc_generator_checkpoint_path: "./best_acc_generator_checkpoint_path.pth"
    final_generator_checkpoint_path: "./final_generator_checkpoint.pth"
    generator_evaluate_path: "./generator_evaluate.csv"



