agent:
    main_agent: "FRSearchAgent"
    training_strategy_agent: "UniformSampler"
    search_strategy_agent: "EvolutionSearcher"
    search_space_agent: "FBNetL"

    criterion_agent: "FaceCELoss"

search_utility:
    directly_search: False
    generation_num: 10
    population_num: 20
    parent_num: 10
    info_metric: "flops"
    target_hc: 300


train:
    resume: False
    random_seed: 1234
    device: "cuda"
    ngpu: 1
    epochs: 10

    bn_track_running_stats: True
    bn_momentum: 0.1

criterion:
    normalize: True
    embedding_channels: 256
    training_classes: 10575
    margin: 0.3 # Margin of triplet loss

dataset:
    dataset: "face_angular"
    dataset_path: "./data/"
    
    classes: 256 # Embedding channels
    input_size: 112

    batch_size: 64
    num_workers: 4
    train_portion: 0.8

optim:
    optimizer: "sgd"
    lr: 0.05
    weight_decay: 0.00004
    momentum: 0.9
    alpha: 0.9
    beta: 0.99

    scheduler: "cosine"
    decay_step: 10
    decay_ratio: 0.1

logs_path:
    logger_path: "./logs/"
    writer_path: "./logs/tb/"


experiment_path:
    resume_path: "./checkpoints/search_1.pth"
    checkpoint_root_path: "./checkpoints/"
    best_checkpoint_path: "./best_checkpoint.pth"

    lookup_table_path: "./lookup_table.json"
    searched_model_path: "./searched_model_architecture.npy"



