agent:
    main_agent: "SearchAgent"
    training_strategy_agent: "UniformSampler"
    search_strategy_agent: "EvolutionSearcher"
    supernet_agent: "ProxylessNASSupernet"

    criterion_agent: "LabelSmoothingCrossEntropy"

target_hc: 100

search_utility:
    directly_search: True
    search_strategy: "evolution"
    generation_num: 10
    population_num: 10
    parent_num: 5
    info_metric: "flops"


train:
    resume: False
    random_seed: 42
    device: "cuda"
    ngpu: 1
    epochs: 5

    bn_track_running_stats: True
    bn_momentum: 0.1

criterion:
    # Margin of triplet loss
    margin: 0.3

dataset:
    dataset: "CASIA-WebFace"
    dataset_path: "./data/"
    
    # Embedding channels
    classes: 100
    input_size: 32

    batch_size: 128
    num_workers: 4
    train_portion: 0.8

optim:
    optimizer: "adam"
    lr: 0.001
    weight_decay: 0.0001
    momentum: 0.9
    alpha: 0.9
    beta: 0.99

    scheduler: "cosine"
    decay_step: 10
    decay_ratio: 0.1

logs_path:
    logger_path: "./logs/"
    writer_path: "./logs/tb/"


experiment_path:
    resume_path: "./best_checkpoint.pth"
    checkpoint_root_path: "./checkpoints/"
    best_checkpoint_path: "./best_checkpoint.pth"

    lookup_table_path: "./lookup_table.json"
    searched_model_path: "./searched_model_architecture.npy"



