agent:
    main_agent: "FRSearchAgent"
    training_strategy_agent: "UniformSampler"
    search_strategy_agent: "EvolutionSearcher"
    search_space_agent: "MobileFaceNet"

    criterion_agent: "OnlineTripletLoss"

search_utility:
    directly_search: False
    generation_num: 10
    population_num: 20
    parent_num: 10
    info_metric: "flops"
    target_hc: 350


train:
    resume: False
    random_seed: 42
    device: "cuda"
    ngpu: 4
    epochs: 5

    bn_track_running_stats: True
    bn_momentum: 0.1

criterion:
    margin: 0.3 # Margin of triplet loss

dataset:
    dataset: "face"
    dataset_path: "./data/"
    
    classes: 128 # Embedding channels
    input_size: 112

    batch_size: 128
    num_workers: 8
    train_portion: 0.8

optim:
    optimizer: "adam"
    lr: 0.001
    weight_decay: 0.0001
    momentum: 0.9
    alpha: 0.9
    beta: 0.99

    scheduler: "cosine"
    decay_step: 10
    decay_ratio: 0.1

logs_path:
    logger_path: "./logs/"
    writer_path: "./logs/tb/"


experiment_path:
    resume_path: "./best_checkpoint.pth"
    checkpoint_root_path: "./checkpoints/"
    best_checkpoint_path: "./best_checkpoint.pth"

    lookup_table_path: "./lookup_table.json"
    searched_model_path: "./searched_model_architecture.npy"



